//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dock
    {
        public Dock()
        {
            this.Ucheniki = new HashSet<Ucheniki>();
        }
    
        public int ID_dock { get; set; }
        public string Seriya_svid { get; set; }
        public string Num_svid { get; set; }
        public Nullable<System.DateTime> Datavid_svid { get; set; }
        public string Kemvid_svid { get; set; }
        public string Seriya_pass { get; set; }
        public string Num_pass { get; set; }
        public Nullable<System.DateTime> Datavid_pass { get; set; }
        public string Kemvid_pass { get; set; }
        public string INN { get; set; }
        public string Snils { get; set; }
        public string Medpolis { get; set; }
    
        public virtual ICollection<Ucheniki> Ucheniki { get; set; }
    }
}
