//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class Family
    {
        public Family()
        {
            this.Ucheniki = new HashSet<Ucheniki>();
        }
    
        public int ID_fam { get; set; }
        public bool Full_fam { get; set; }
        public bool Sirota_fam { get; set; }
        public bool Lowincome_fam { get; set; }
        public bool Dysfunctional_fam { get; set; }
        public bool Foster_fam { get; set; }
        public bool Large_fam { get; set; }
    
        public virtual ICollection<Ucheniki> Ucheniki { get; set; }
    }
}
