//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class Klasses
    {
        public Klasses()
        {
            this.Konkurs = new HashSet<Konkurs>();
            this.Meropriyatia = new HashSet<Meropriyatia>();
            this.Ucheniki = new HashSet<Ucheniki>();
        }
    
        public int ID_klass { get; set; }
        public string N_klass { get; set; }
        public int KlRuk_id { get; set; }
    
        public virtual KlRuks KlRuks { get; set; }
        public virtual ICollection<Konkurs> Konkurs { get; set; }
        public virtual ICollection<Meropriyatia> Meropriyatia { get; set; }
        public virtual ICollection<Ucheniki> Ucheniki { get; set; }
    }
}
