//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class KlRuks
    {
        public KlRuks()
        {
            this.Klasses = new HashSet<Klasses>();
        }
    
        public int ID_klruk { get; set; }
        public string F_klruk { get; set; }
        public string I_klruk { get; set; }
        public string O_klruk { get; set; }
        public int User_id { get; set; }
    
        public virtual ICollection<Klasses> Klasses { get; set; }
        public virtual Users Users { get; set; }
    }
}
