//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class Languages
    {
        public Languages()
        {
            this.Ucheniki = new HashSet<Ucheniki>();
        }
    
        public int ID_lang { get; set; }
        public string N_lang { get; set; }
    
        public virtual ICollection<Ucheniki> Ucheniki { get; set; }
    }
}
