//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class LevelKonkurs
    {
        public LevelKonkurs()
        {
            this.Konkurs = new HashSet<Konkurs>();
        }
    
        public int ID_level { get; set; }
        public string N_level { get; set; }
    
        public virtual ICollection<Konkurs> Konkurs { get; set; }
    }
}
