//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meropriyatia
    {
        public int ID_mer { get; set; }
        public string N_mer { get; set; }
        public string Opisanie { get; set; }
        public int Klass_id { get; set; }
        public int Status_id { get; set; }
        public System.DateTime Data_mer { get; set; }
        public int Vidmer_id { get; set; }
    
        public virtual Klasses Klasses { get; set; }
        public virtual StatusMer StatusMer { get; set; }
        public virtual VidMer VidMer { get; set; }
    }
}
