//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyClass
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Dock> Dock { get; set; }
        public DbSet<Family> Family { get; set; }
        public DbSet<Klasses> Klasses { get; set; }
        public DbSet<KlRuks> KlRuks { get; set; }
        public DbSet<Konkurs> Konkurs { get; set; }
        public DbSet<Languages> Languages { get; set; }
        public DbSet<LevelKonkurs> LevelKonkurs { get; set; }
        public DbSet<Meropriyatia> Meropriyatia { get; set; }
        public DbSet<Obrazovanie> Obrazovanie { get; set; }
        public DbSet<Pol> Pol { get; set; }
        public DbSet<Roditeli> Roditeli { get; set; }
        public DbSet<RodUch> RodUch { get; set; }
        public DbSet<StatusMer> StatusMer { get; set; }
        public DbSet<Ucheniki> Ucheniki { get; set; }
        public DbSet<Users> Users { get; set; }
        public DbSet<VidMer> VidMer { get; set; }
        public DbSet<Vidrods> Vidrods { get; set; }
    }
}
