//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class Obrazovanie
    {
        public Obrazovanie()
        {
            this.Roditeli = new HashSet<Roditeli>();
        }
    
        public int ID_obr { get; set; }
        public string N_obr { get; set; }
    
        public virtual ICollection<Roditeli> Roditeli { get; set; }
    }
}
