//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class RodUch
    {
        public int ID_rd { get; set; }
        public int Rod_id { get; set; }
        public int Uch_id { get; set; }
    
        public virtual Roditeli Roditeli { get; set; }
        public virtual Ucheniki Ucheniki { get; set; }
    }
}
