//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.KlRuks = new HashSet<KlRuks>();
        }
    
        public int ID_user { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public int Level { get; set; }
    
        public virtual ICollection<KlRuks> KlRuks { get; set; }
    }
}
